apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: registry.gitlab.com/boobsrate/core
      context: .
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: boobsrate-core
        namespace: boobsrate
        chartPath: deploy/boobsrate-core
        values:
          image: registry.gitlab.com/boobsrate/core
        setValues:
          image.pullPolicy: Always
        wait: true
        imageStrategy:
          helm: {}
    flags:
      install:
        - --atomic
      upgrade:
        - --atomic
