image:
  env:
    - name: MINIO_BUCKET
      value: "tits"
    - name: TRACER_NAME
      value: "tits"
    - name: ENV
      value: "dev"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: "letsencrypt-prod-dns"
    external-dns.alpha.kubernetes.io/hostname: "dev.rate-tits.akuzyashin.pw"
    nginx.ingress.kubernetes.io/server-snippets: |
      location /api/ws {
         proxy_set_header Upgrade $http_upgrade;
         proxy_http_version 1.1;
         proxy_set_header X-Forwarded-Host $http_host;
         proxy_set_header X-Forwarded-Proto $scheme;
         proxy_set_header X-Forwarded-For $remote_addr;
         proxy_set_header Host $host;
         proxy_set_header Connection "upgrade";
         proxy_cache_bypass $http_upgrade;
       }
  hosts:
    - host: dev.rate-tits.akuzyashin.pw
      paths:
        - path: /api/(.*)
          pathType: Prefix
          backend:
            service:
              port:
                number: 8088

  tls:
    - secretName: tls-titsfrontend-dev
      hosts:
        - dev.rate-tits.akuzyashin.pw