apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "boobsrate-core.fullname" . }}-downloader-{{ randAlphaNum 6 | lower }}
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ include "boobsrate-core.name" . }}-downloader
            chart: {{ include "boobsrate-core.chart" . }}
            release: {{ .Release.Name }}
            heritage: {{ .Release.Service }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          restartPolicy: Never
          containers:
            - name: {{ .Chart.Name }}-downloader
              image: "{{ .Values.image.name }}"
            {{- if .Values.image.env }}
              env:
                {{- range .Values.image.env }}
                - name: {{ .name }}
                  value: {{ .value | quote }}
                {{- end }}
              {{- end }}
              {{- if .Values.image.envFromSecret }}
              {{- range .Values.image.envFromSecret }}
                - name: {{.name | quote }}
                  valueFrom:
                    secretKeyRef:
                      name: {{ .valueFrom.secretKeyRef.name }}
                      key: {{ .valueFrom.secretKeyRef.key }}
                {{- end }}
              {{- end }}
              imagePullPolicy: Always
              command: [ {{ .Values.image.init_command }} ]
